[versions]
# Plugins
spotless = "8.1.0"
idea_ext = "1.3"

# Tools
google-java-format = "1.33.0"
lombok = "1.18.42"

# Testing
junit = "6.0.2"
mockito = "5.21.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# Testing
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
idea_ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea_ext" }
